# Generated by Django 5.1.3 on 2025-11-17 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_appointment_time_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
