# Generated by Django 5.1.3 on 2025-11-18 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_alter_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('under_medication', models.BooleanField(default=False)),
                ('had_recent_illness', models.BooleanField(default=False)),
                ('illness_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_donor_profile', to='userapp.user')),
            ],
            options={
                'unique_together': {('user',)},
            },
        ),
    ]
