# Generated by Django 5.1.3 on 2025-11-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_blooddonor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blooddonor',
            old_name='weight_kg',
            new_name='weight',
        ),
    ]
