# Generated by Django 5.1.3 on 2025-11-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_rename_weight_kg_blooddonor_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonor',
            name='location',
            field=models.CharField(choices=[('Thrissur', 'thrissur'), ('Ernakulam', 'ernankulam'), ('Palakkad', 'palakkad')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
