# Generated by Django 5.1.3 on 2025-11-26 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditrackapp', '0012_notification'),
        ('userapp', '0010_blooddonor_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='meditrackapp.doctor'),
        ),
    ]
