# Generated by Django 5.1.3 on 2025-11-27 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_alter_appointment_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('donation_type', models.CharField(choices=[('Whole Blood', 'Whole Blood'), ('Red Cells', 'Red Cells'), ('Plasma', 'Plasma'), ('Platelets', 'Platelets')], max_length=50)),
                ('units', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_records', to='userapp.blooddonor')),
            ],
        ),
    ]
