# Generated by Django 5.1.3 on 2025-11-28 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditrackapp', '0017_notification_type'),
        ('userapp', '0012_donationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('completed', 'Completed')], default='accepted', max_length=20)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.blooddonor')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meditrackapp.bloodrequest')),
            ],
        ),
    ]
