# Generated by Django 5.1.3 on 2025-11-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditrackapp', '0010_reschedulerequest_delete_emergencyrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reschedulerequest',
            name='admin_note',
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
