# Generated by Django 5.1.3 on 2025-11-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meditrackapp', '0012_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
