# Generated by Django 5.1.3 on 2025-11-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditrackapp', '0014_bloodrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='donation_type',
            field=models.CharField(choices=[('Whole Blood', 'Whole Blood'), ('Red Cells', 'Red Cells'), ('Plasma', 'Plasma'), ('Platelets', 'Platelets')], default='whole_blood', max_length=20),
        ),
    ]
