# Generated by Django 5.1.3 on 2025-11-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditrackapp', '0015_bloodrequest_donation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='donation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='donation_type',
            field=models.CharField(choices=[('Whole Blood', 'Whole Blood'), ('Red Cells', 'Red Cells'), ('Plasma', 'Plasma'), ('Platelets', 'Platelets')], default='Whole Blood', max_length=20),
        ),
    ]
