# Generated by Django 5.1.3 on 2025-11-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditrackapp', '0016_remove_bloodrequest_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('blood', 'Blood Donation'), ('reschedule', 'Reschedule Request')], default='blood', max_length=20),
        ),
    ]
